### ISSUE TITLE
how to pass the unsafe flag

### ISSUE THREAD

**Issue by uricwk** [marcduez/openapi-to-joi#2]
Thank you for this, it's very useful.

I'm struggling to figure out how to pass the `unsafe()` flag.
AFAIK OpenAPI doesn't have this option, however, I've seen the code thinks it can handle it:

```javascript
var appendUnsafe = function (parts, description) {
    var flags = description.flags;
    if ((flags === null || flags === void 0 ? void 0 : flags.unsafe) === true) {
        parts.push(".unsafe()");
    }
};
```

However, in my yaml, I can't seem to be able to figure out where this goes.

I was trying various combinations of this
```yaml
properties:
  SomeNumber:
    type: number
    unsafe: true
    description: Some large unsafe number
    example: 5.2777000098765434e+23
```

But none seem to work. Not sure if it's a bug report, more like update docs maybe?

Anyway, Thank you.

Edit: Another related issue i'm having is that I am unable to disable the `.unknown()` option
